# Generated by Django 6.0 on 2026-01-03 06:56

import django.db.models.deletion
import django.db.models.expressions
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creater_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('display_name', models.CharField(default=django.db.models.expressions.CombinedExpression(models.Value('user'), '+', models.F('user.id')), max_length=20)),
                ('bio', models.CharField(default='')),
                ('avatar', models.ImageField(upload_to='avatars/')),
                ('birth_date', models.DateField(default=None)),
                ('social_links', models.JSONField(default='{}')),
                ('is_public', models.BooleanField(default=True)),
                ('show_email', models.BooleanField(default=True)),
                ('show_social_links', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
