# Generated by Django 6.0 on 2026-01-03 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='social_links',
            field=models.JSONField(default={}),
        ),
    ]
