# Generated by Django 6.0 on 2026-01-03 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_alter_profile_birth_date_alter_profile_display_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(default='avatars/ffdc447144ade4b88224f0f4202aa22e.jpg', upload_to='avatars/'),
        ),
    ]
