# Generated by Django 6.0 on 2026-01-04 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_alter_profile_bio_alter_profile_birth_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='social_links',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
